LEVEL=../../../..

LIBRARYNAME = part2

LOADABLE_MODULE = 1

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

LIBS += -lflowfunction -llattices -lworklist

#USEDLIBS += Helper
